SET NAMES UTF8;
DROP DATABASE IF EXISTS music_play;
CREATE DATABASE music_play CHARSET=utf8;
USE music_play;
CREATE TABLE m_user(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(20) NOT NULL DEFAULT '',
    upwd VARCHAR(32) NOT NULL DEFAULT ''
);
INSERT INTO m_user VALUES(1,'alvinbb','123456');
CREATE TABLE m_music_list(
    mid INT PRIMARY KEY AUTO_INCREMENT,
    mname VARCHAR(20) NOT NULL DEFAULT '',
    pic VARCHAR(20) NOT NULL DEFAULT '',
    msrc VARCHAR(20) NOT NULL DEFAULT ''
);